name: Frontend CI - Build and Lint

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        
        node-version: 18.x

    #  Dependency Installation 
    - name: Install client dependencies
      run: npm install
      working-directory: ./client

    # Testing and Code Quality 
    - name: Run Frontend Unit Tests
      run: npm test
      working-directory: ./client
      continue-on-error: true 

    - name: Run Lint and Code Quality Check
      run: npx eslint ./src --fix --quiet
      working-directory: ./client
      
    # Production Build 
    - name: Build Production Assets
      run: npm run build
      working-directory: ./client
      env:
        VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        
    - name: Upload Build Artifact (For Vercel or manual deployment)
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-artifact
        path: client/dist
        